import {z} from 'zod';
import type {Assessment,ImageAssessmentProvider} from './provider.service.js';

export const coverageResultSchema=z.object({verdict:z.enum(['MATCH','WRONG_ITEM','MISSING_SURFACE','UNCERTAIN']),observedFixture:z.string().max(100),observedView:z.string().max(100),observedLabel:z.string().max(100).nullable(),identityConsistent:z.boolean(),privacyFlag:z.boolean(),reasonCode:z.enum(['CLEAN','WRONG_ITEM','MISSING_SURFACE','IDENTITY_UNCERTAIN','CONTEXT_UNCERTAIN','PRIVACY_HOLD'])}).strict();
export type CoverageResult=z.infer<typeof coverageResultSchema>;
export const contextCoverageExpectedSchema=z.object({contextKey:z.enum(['ENTRANCE','LAYOUT'])}).strict();
export type ContextCoverageExpected=z.infer<typeof contextCoverageExpectedSchema>;
export type FixtureCoverageExpected={fixture:string;view:string;order?:number;itemCodeSnapshot?:string;nameSnapshot?:string;sourceAreaItemId?:number;identity?:{mode?:string;existingNumber?:string|null}};
export type CoverageExpected=ContextCoverageExpected|FixtureCoverageExpected;
export interface CoverageProvider{evaluate(image:Buffer,expected:CoverageExpected,context:Buffer[],candidates:Buffer[]):Promise<Assessment<z.infer<typeof coverageResultSchema>>>;}
export async function assessCoverage(provider:ImageAssessmentProvider,image:Buffer,expected:unknown,context:Buffer[]=[],candidates:Buffer[]=[]){const assessment=await provider.assess('coverage',`Assess fixture/view and identity only, never cleanliness or GPS. For expected contextKey ENTRANCE or LAYOUT, assess room context: ENTRANCE must show the entrance/room marker and LAYOUT must show the fixture arrangement. A MATCH must report observedFixture ROOM_CONTEXT and observedView exactly the expected contextKey. An arbitrary fixture close-up cannot satisfy room context; missing or ambiguous room context must be MISSING_SURFACE or UNCERTAIN with CONTEXT_UNCERTAIN. Privacy remains an independent assessment. First image is current evidence, then ${context.length} session context images, then duplicate candidates. Similar-looking fixtures are legitimate; similarity alone is not wrongdoing. Unlabelled indistinguishable fixtures require UNCERTAIN and targeted wider context. Compare the immutable itemCodeSnapshot, nameSnapshot and sourceAreaItemId alongside route order, visible number/label and surroundings. PRINTED_LABEL requires the visible human label to exactly match nameSnapshot or itemCodeSnapshot; EXISTING_NUMBER requires the exact recorded existingNumber. Missing or mismatched labels cannot establish identity. Expected snapshot: ${JSON.stringify(expected)}. JSON fields: verdict (MATCH/WRONG_ITEM/MISSING_SURFACE/UNCERTAIN), observedFixture, observedView, observedLabel (string/null), identityConsistent (boolean), privacyFlag (boolean), reasonCode (CLEAN/WRONG_ITEM/MISSING_SURFACE/IDENTITY_UNCERTAIN/CONTEXT_UNCERTAIN/PRIVACY_HOLD).`,[image,...context,...candidates],coverageResultSchema);
 const result=coverageResultSchema.parse(assessment.result);
 if(result.privacyFlag){if(result.reasonCode!=='PRIVACY_HOLD')throw new Error('PROVIDER_MALFORMED');return {...assessment,result};}
 const e=expected as {fixture?:string;view?:string;identity?:{mode?:string;existingNumber?:string};contextKey?:unknown;itemCodeSnapshot?:string;nameSnapshot?:string;sourceAreaItemId?:number};
 if('contextKey' in e){const contextExpected=contextCoverageExpectedSchema.parse(expected);if(result.verdict==='MATCH'&&(result.observedFixture!=='ROOM_CONTEXT'||result.observedView!==contextExpected.contextKey))throw new Error('PROVIDER_MALFORMED');}
 if(result.verdict==='MATCH'&&(!result.identityConsistent||result.reasonCode!=='CLEAN'||e.fixture&&result.observedFixture!==e.fixture||e.view&&result.observedView!==e.view||e.identity?.mode==='EXISTING_NUMBER'&&(!e.identity.existingNumber?.trim()||result.observedLabel!==e.identity.existingNumber)))throw new Error('PROVIDER_MALFORMED');
 if(result.verdict==='MATCH'&&e.identity?.mode==='PRINTED_LABEL'&&(!result.observedLabel||![e.nameSnapshot,e.itemCodeSnapshot].filter(v=>typeof v==='string'&&!!v).includes(result.observedLabel)))throw new Error('PROVIDER_MALFORMED');
 if(result.privacyFlag&&result.reasonCode!=='PRIVACY_HOLD')throw new Error('PROVIDER_MALFORMED');
 return {...assessment,result};}
export const privacyResultSchema=z.object({status:z.enum(['SAFE','HOLD','UNCERTAIN']),reasonCode:z.enum(['CLEAN','PRIVACY_HOLD'])}).strict();
export async function assessPrivacy(provider:ImageAssessmentProvider,image:Buffer){const assessment=await provider.assess('privacy','Check for occupants, body/private content, or reflections showing people. No facial identification. Ambiguity must be UNCERTAIN. JSON: status SAFE/HOLD/UNCERTAIN, reasonCode CLEAN/PRIVACY_HOLD.',[image],privacyResultSchema);const result=privacyResultSchema.parse(assessment.result);if((result.status==='SAFE')!==(result.reasonCode==='CLEAN'))throw new Error('PROVIDER_MALFORMED');return {...assessment,result};}
