import {z} from 'zod';
export const benchmarkRowsSchema=z.array(z.object({id:z.string().min(1),roomId:z.string().min(1),fixtureId:z.string().min(1),fixtureType:z.string().min(1),split:z.enum(['development','heldout']),consented:z.literal(true),visibility:z.enum(['ASSESSABLE','UNASSESSABLE']),identity:z.enum(['CORRECT','WRONG','REPLAYED']),cleanliness:z.enum(['CLEAN','NEEDS_ATTENTION','DIRTY','CANNOT_ASSESS']),predictedCleanliness:z.enum(['CLEAN','NEEDS_ATTENTION','DIRTY','CANNOT_ASSESS','SERVICE_FAILURE']),wouldAutoPass:z.boolean(),provider:z.string().min(1),model:z.string().min(1),requestedModel:z.string().min(1).optional(),promptVersion:z.string().min(1),rubricVersion:z.number().int().positive(),latencyMs:z.number().nonnegative(),costUsd:z.number().nonnegative().nullable()}).strict());
type Row=z.infer<typeof benchmarkRowsSchema>[number];
function interval(errors:number,n:number){if(!n)return null;const z=1.96,p=errors/n,d=1+z*z/n,c=(p+z*z/(2*n))/d,h=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/d;return [Math.max(0,c-h),Math.min(1,c+h)];}
function metrics(rows:Row[]){const dirty=rows.filter(r=>r.cleanliness==='DIRTY'),wrong=rows.filter(r=>r.identity!=='CORRECT'),falseClean=dirty.filter(r=>r.predictedCleanliness==='CLEAN').length,wrongPass=wrong.filter(r=>r.wouldAutoPass).length;return {examples:rows.length,dirty:dirty.length,wrongOrReplayed:wrong.length,falseClean,wrongAutoPasses:wrongPass,falseClean95:interval(falseClean,dirty.length),wrongAutoPass95:interval(wrongPass,wrong.length),serviceFailures:rows.filter(r=>r.predictedCleanliness==='SERVICE_FAILURE').length,targetMet:dirty.length>=100&&wrong.length>=100&&falseClean/dirty.length<=.02&&wrongPass===0};}
/** Offline evidence report; never changes deployment eligibility. */
export function benchmarkReport(input:unknown){
 const rows=benchmarkRowsSchema.parse(input),ids=new Set<string>(),rooms=new Map<string,string>(),fixtures=new Map<string,string>();
 for(const r of rows){if(ids.has(r.id))throw new Error('Duplicate example ID');ids.add(r.id);for(const [map,key] of [[rooms,r.roomId],[fixtures,r.fixtureId]] as const){if(map.has(key)&&map.get(key)!==r.split)throw new Error('Room/fixture split leakage');map.set(key,r.split);}}
 const heldout=rows.filter(r=>r.split==='heldout'),configurations=new Set(heldout.map(r=>JSON.stringify([r.provider,r.model,r.requestedModel??null,r.promptVersion,r.rubricVersion])));
 if(configurations.size>1)throw new Error('Evaluate one configuration per report');
 const types=[...new Set(heldout.map(r=>r.fixtureType))].sort();
 return {status:heldout.length?'MEASURED':'DATASET_UNAVAILABLE',autoPassEnabled:false,configuration:configurations.size?[...configurations][0]:null,overall:metrics(heldout),perFixture:Object.fromEntries(types.map(t=>[t,metrics(heldout.filter(r=>r.fixtureType===t))])),meanLatencyMs:heldout.length?heldout.reduce((n,r)=>n+r.latencyMs,0)/heldout.length:null,measuredCostUsd:heldout.length&&heldout.every(r=>r.costUsd!==null)?heldout.reduce((n,r)=>n+r.costUsd!,0):null,limitations:['Independent human labels and consent are required.','95% Wilson intervals express sampling uncertainty.','Meeting targets does not enable auto-pass; sparse types remain review-required.']};
}
