import {describe,it,expect} from 'vitest';
import {requirementDecision,completionEligibility,sessionWindows,reduceSession,reduceRequirement,aggregateItems,reduceTaskVerification,escalationDecision,presenceDecision,classifyTiming} from './verificationPolicy.service.js';
const end=new Date('2026-10-04T10:00:00Z');
const eligible={requirements:[{mandatory:true,state:'PASSED'}],presenceAcceptable:true,contextAcceptable:true,blockingIssues:false,hasManualOverride:false,assignmentCurrent:true};
describe('independent decisions and reducers',()=>{
 it('never maps quality, uncertainty or outages to dirt or clean',()=>{expect(requirementDecision({serviceFailure:true,cleanliness:'CLEAN'})).toBe('SERVICE_FAILURE');expect(requirementDecision({qualityPass:false,cleanliness:'DIRTY'})).toBe('RECAPTURE_REQUIRED');expect(requirementDecision({coverage:'WRONG_ITEM',cleanliness:'DIRTY'})).toBe('RECAPTURE_REQUIRED');expect(requirementDecision({coverage:'MATCH',cleanliness:'CLEAN',surfaceVerdicts:['CANNOT_ASSESS']})).toBe('RECAPTURE_REQUIRED');expect(requirementDecision({privacyHold:true,serviceFailure:true})).toBe('PRIVACY_HOLD');});
 it('requires all visible surfaces and coverage before passing',()=>{expect(requirementDecision({coverage:'MATCH',cleanliness:'CLEAN',surfaceVerdicts:['CLEAN']})).toBe('PASSED');expect(requirementDecision({cleanliness:'CLEAN'})).toBe('REVIEW_REQUIRED');});
 it('requires a nonempty mandatory set, assignment and integrity gates',()=>{expect(completionEligibility(eligible)).toBe('VERIFIED_COMPLETE');for(const patch of [{requirements:[]},{assignmentCurrent:false},{blockingIssues:true},{contextAcceptable:false},{presenceAcceptable:false}])expect(completionEligibility({...eligible,...patch})).toBeNull();});
 it('waivers do not override presence; explicit context override produces exceptions',()=>{const requirements=[{mandatory:true,state:'WAIVED'}];expect(completionEligibility({...eligible,requirements})).toBe('COMPLETED_WITH_EXCEPTIONS');expect(completionEligibility({...eligible,requirements,presenceAcceptable:false})).toBeNull();expect(completionEligibility({...eligible,presenceAcceptable:false,hasManualOverride:true})).toBe('COMPLETED_WITH_EXCEPTIONS');});
 it('ignores optional view failures but rejects mandatory items without required views',()=>{expect(aggregateItems([{mandatory:true,requirements:[{mandatory:true,state:'PASSED'}]},{mandatory:false,requirements:[{mandatory:true,state:'MISSING'}]}]).requirements).toHaveLength(1);expect(aggregateItems([{mandatory:true,requirements:[]}]).valid).toBe(false);});
 it('preserves passed views and rejects stale asynchronous generations',()=>{const state={state:'PASSED',decisionVersion:4,currentAttemptId:'a'};expect(reduceRequirement(state,{type:'RETRY',expectedVersion:4,attemptId:'b'})).toBe(state);const pending={...state,state:'PROCESSING',currentAttemptId:'b'};expect(reduceRequirement(pending,{type:'RESULT',expectedVersion:3,attemptId:'a',state:'PASSED'})).toBe(pending);expect(reduceRequirement(pending,{type:'RESULT',expectedVersion:4,attemptId:'a',state:'PASSED'})).toBe(pending);});
 it('keeps terminal session and task states monotonic',()=>{expect(reduceSession('REVOKED','RESUME')).toBe('REVOKED');expect(reduceSession('ACTIVE','PAUSE')).toBe('PAUSED');expect(reduceTaskVerification('VERIFIED',{capturing:false,processing:false,review:true,rework:true,outcome:null})).toBe('VERIFIED');});
 it('bounds capture/upload windows and rejects missed starts or rolling extensions',()=>{expect(sessionWindows(new Date(+end+25*60000),end,undefined,new Date(+end-1000)).captureExpiresAt).toEqual(new Date(+end+30*60000));expect(()=>sessionWindows(end,end,undefined,null)).toThrow();expect(()=>sessionWindows(end,end,undefined,end,121)).toThrow();});
 it('separates server receipt, device timing, lateness and uncertainty',()=>{expect(classifyTiming(end,end,end,new Date(+end+60000),false)).toBe('ON_TIME_SERVER_OBSERVED');expect(classifyTiming(end,end,null,new Date(+end+60000),true)).toBe('ON_TIME_DEVICE_REPORTED');expect(classifyTiming(new Date(+end+1),end,null,new Date(+end+60000),true)).toBe('LATE');expect(classifyTiming(end,end,null,new Date(+end+60000),false)).toBe('UNCERTAIN');});
 it('keeps service retries separate from staff failure counters',()=>{expect(escalationDecision('CLEANING',2)).toBe('STAFF_ACTION_REQUIRED');expect(escalationDecision('RECAPTURE',3)).toBe('MANAGER_REVIEW');expect(escalationDecision('SERVICE',99)).toBe('RETRY_SERVICE');expect(escalationDecision('INTEGRITY',0)).toBe('IMMEDIATE_REVIEW');});
 it('does not expand a geofence to accommodate uncertainty',()=>{expect(presenceDecision({distance:30,accuracy:20,ageSeconds:10,radius:50}).status).toBe('ACCEPTABLE');expect(presenceDecision({distance:45,accuracy:20,ageSeconds:10,radius:50}).status).toBe('UNCERTAIN');expect(presenceDecision({distance:100,accuracy:20,ageSeconds:10,radius:50}).status).toBe('OUTSIDE');expect(presenceDecision({distance:0,accuracy:51,ageSeconds:10,radius:50}).reasonCode).toBe('GPS_INACCURATE');});
});

import {reduceAttempt,validateCaptureTiming,reduceIssue} from './verificationPolicy.service.js';
describe('attempt and issue transitions',()=>{
 it('permits each processing dependency in order and preserves terminal decisions',()=>{let state='RESERVED';for(const next of ['STORING','RECEIVED','QUALITY_CHECK','COVERAGE_CHECK','CLEANLINESS_CHECK','PASSED'])state=reduceAttempt(state,next);expect(state).toBe('PASSED');expect(()=>reduceAttempt(state,'CLEANING_REQUIRED')).toThrow();expect(()=>reduceAttempt('RECEIVED','PASSED')).toThrow();});
 it('separates privacy and service branches from cleaning outcomes',()=>{expect(reduceAttempt('QUALITY_CHECK','PRIVACY_HOLD')).toBe('PRIVACY_HOLD');expect(reduceAttempt('COVERAGE_CHECK','RETRY_WAIT')).toBe('RETRY_WAIT');expect(reduceAttempt('RETRY_WAIT','COVERAGE_CHECK')).toBe('COVERAGE_CHECK');expect(()=>reduceAttempt('SERVICE_FAILURE','PASSED')).toThrow();});
 it('detects reboot and contradictory device clocks without a cleanliness verdict',()=>{const input={issuedAt:end,claimedCapturedAt:end,elapsedMs:0,sessionBootId:'a',captureBootId:'a',receivedAt:end};expect(validateCaptureTiming(input)).toBe(true);expect(validateCaptureTiming({...input,captureBootId:'b'})).toBe(false);expect(validateCaptureTiming({...input,claimedCapturedAt:new Date(+end+120000)})).toBe(false);});
 it('reopens the same case issue only on a new failure',()=>{expect(reduceIssue('RESOLVED','REVIEW')).toBe('RESOLVED');expect(reduceIssue('RESOLVED','REOPEN')).toBe('OPEN');expect(reduceIssue('MANAGER_REVIEW','SATISFIED')).toBe('RESOLVED');});
});
